<#
.SYNOPSIS
    Writes Plugins\plugins.json (the engine's plugin allowlist) with the SHA-256
    of every staged plugin DLL.

.DESCRIPTION
    HexEngine.Core's PluginSystem reads <install>\Plugins\plugins.json. A listed
    plugin whose file hash does not match is REFUSED in every load policy, so
    the shipped plugins are integrity-checked at start-up. Unlisted DLLs a user
    drops in still load under the default (developer) policy.

    MUST run after code signing: Authenticode signing rewrites the DLL, which
    changes its hash.

.PARAMETER StagingDir
    The staged release (dist\HexEngine).
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$StagingDir
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Absolute: .NET file APIs resolve relative paths against the process directory,
# not PowerShell's current location.
$StagingDir = (Resolve-Path -LiteralPath $StagingDir).Path
$pluginDir = Join-Path $StagingDir 'Plugins'
$dlls = @(Get-ChildItem -LiteralPath $pluginDir -Filter '*.dll' -File | Sort-Object Name)
if ($dlls.Count -eq 0) { throw "No plugin DLLs found in $pluginDir." }

$entries = foreach ($d in $dlls) {
    $name = $d.BaseName -replace '^HexEngine\.', '' -replace 'Plugin$', ''
    [ordered]@{
        name    = $name
        module  = $d.Name
        enabled = $true
        sha256  = (Get-FileHash -LiteralPath $d.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    }
}

$manifest = [ordered]@{
    _comment = 'Generated by scripts/release/New-PluginManifest.ps1 at release time. A listed plugin whose SHA-256 does not match is refused. Do not edit by hand; reinstall to repair.'
    plugins  = @($entries)
}
$path = Join-Path $pluginDir 'plugins.json'
# UTF-8 without BOM regardless of PowerShell edition.
[IO.File]::WriteAllText($path, ($manifest | ConvertTo-Json -Depth 4), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $path ($($dlls.Count) plugins)"
