
#pragma once

#include "Environment/IEnvironment.hpp"
#include "Environment/TimeManager.hpp"
#include "Environment/LogFile.hpp"
#include "Environment/IGameExtension.hpp"
#include "Environment/ClassRegistry.hpp"
#include "Environment/HeadlessEnvironment.hpp"
#include "Environment/Game3DEnvironment.hpp"

#include "FileSystem/FileSystem.hpp"
#include "FileSystem/ResourceSystem.hpp"
#include "FileSystem/KeyValues.hpp"
#include "FileSystem/ICompressionProvider.hpp"
#include "FileSystem/AssetFile.hpp"
#include "FileSystem/SceneSaveFile.hpp"
#include "FileSystem/ProjectFile.hpp"
#include "FileSystem/AssetPackage.hpp"
#include "FileSystem/AssetPackageManager.hpp"
#include "FileSystem/DiskFile.hpp"

#include "Scripting/ScriptFile.hpp"
#include "Scripting/IScriptEngine.hpp"

#include "Graphics/IGraphicsDevice.hpp"
#include "Graphics/ShaderSystem.hpp"
#include "Graphics/Window.hpp"
#include "Graphics/DebugRenderer.hpp"
#include "Graphics/IFontImporter.hpp"
#include "Graphics/ISSAOProvider.hpp"
#include "Graphics/IFontResource.hpp"
#include "Graphics/IconService.hpp"
#include "Graphics/IStreamlineProvider.hpp"
#include "Graphics/IDenoiserProvider.hpp"

#include "Scene/IModelSystem.hpp"
#include "Scene/SceneManager.hpp"
#include "Scene/MeshPrimitives.hpp"
#include "Scene/SceneRenderer.hpp"
#include "Scene/AnimatedMesh.hpp"
#include "Scene/INavMeshProvider.hpp"
#include "Scene/Prefab.hpp"

#include "Input/InputSystem.hpp"
#include "Input/CommandManager.hpp"
#include "Input/InputSystem.hpp"
#include "Input/HCommand.hpp"
#include "Input/Console.hpp"

#include "Physics/IPhysicsSystem.hpp"
#include "Physics/PhysUtils.hpp"

#include "GUI/DebugGUI.hpp"
#include "GUI/UIManager.hpp"
#include "GUI/Elements/Dock.hpp"
#include "GUI/Elements/Button.hpp"
#include "GUI/Elements/Dialog.hpp"
#include "GUI/Elements/GroupBox.hpp"
#include "GUI/Elements/LineEdit.hpp"
#include "GUI/Elements/ListBox.hpp"
#include "GUI/Elements/MenuBar.hpp"
#include "GUI/Elements/Point.hpp"
#include "GUI/Elements/Style.hpp"
#include "GUI/Elements/TabView.hpp"
#include "GUI/Elements/TreeList.hpp"
#include "GUI/Elements/VerticalLayout.hpp"
#include "GUI/Elements/ContextMenu.hpp"
#include "GUI/Elements/ComponentWidget.hpp"
#include "GUI/Elements/Vector3Edit.hpp"
#include "GUI/Elements/Checkbox.hpp"
#include "GUI/Elements/DragFloat.hpp"
#include "GUI/Elements/DropDown.hpp"
#include "GUI/Elements/DragInt.hpp"
#include "GUI/Elements/ColourPicker.hpp"
#include "GUI/Elements/LineEditDialog.hpp"
#include "GUI/Elements/LoadingDialog.hpp"
#include "GUI/Elements/Vector2Edit.hpp"
#include "GUI/Elements/EntityList.hpp"
#include "GUI/Elements/ArrayElement.hpp"
#include "GUI/Elements/ScrollView.hpp"
#include "GUI/Elements/AssetSearch.hpp"

#include "Terrain/ChunkManager.hpp"
#include "Terrain/HeightMapGenerator.hpp"
#include "Terrain/TerrainGenerator.hpp"

#include "Entity/Component/InteractionComponent.hpp"
#include "Entity/Component/SpotLight.hpp"
#include "Entity/Component/StaticMeshComponent.hpp"
#include "Entity/Component/FirstPersonCameraController.hpp"
#include "Entity/Component/RigidBody.hpp"
#include "Entity/Component/MotorComponent.hpp"
#include "Entity/Component/Billboard.hpp"
#include "Entity/Component/RTSCameraController.hpp"
#include "Entity/Component/PointLight.hpp"
#include "Entity/Component/ThirdPersonCameraController.hpp"
#include "Entity/Component/TimedLifetimeComponent.hpp"
#include "Entity/Component/HingeJoint.hpp"
#include "Entity/Component/ScriptComponent.hpp"
#include "Entity/Component/NavigationComponent.hpp"
#include "Entity/Component/SkeletalAnimationComponent.hpp"
#include "Entity/Component/DayNightCycleComponent.hpp"

#include "Plugin/PluginSystem.hpp"

#include "Audio/AudioManager.hpp"

#include "Math/FloatMath.hpp"
