// D3D11 backend for FidelityFX FSR 2.2 - see ffx_fsr2_dx11.h.

#include <windows.h>
#include <d3d11.h>
#include <d3dcompiler.h>
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include <wchar.h>

#include "ffx_fsr2_dx11.h"

// Pass blobs generated by CompileShaders.cmd (fxc /Fh, cs_5_0).
#include "fsr2_depth_clip.h"
#include "fsr2_reconstruct_previous_depth.h"
#include "fsr2_lock.h"
#include "fsr2_accumulate.h"
#include "fsr2_accumulate_sharpen.h"
#include "fsr2_rcas.h"
#include "fsr2_compute_luminance_pyramid.h"
#include "fsr2_autogen_reactive.h"
#include "fsr2_tcr_autogen.h"

namespace
{
	constexpr uint32_t kMaxResources = 64;		// static grow up from 1, dynamic (per-frame registered) down from the top
	constexpr uint32_t kMaxGpuJobs = 32;
	constexpr uint32_t kMaxUavMips = 16;
	constexpr uint32_t kMaxSrvSlots = 32;
	constexpr uint32_t kMaxUavSlots = 8;		// D3D11.0 compute UAV slot count
	constexpr uint32_t kMaxCbSlots = FFX_MAX_NUM_CONST_BUFFERS;
	constexpr uint32_t kCbBytes = FFX_MAX_CONST_SIZE * sizeof(uint32_t);

	FfxFsr2Dx11LogFunc g_log = nullptr;

	void Log(const char* fmt, ...)
	{
		if (g_log == nullptr)
			return;
		char buffer[512];
		va_list args;
		va_start(args, fmt);
		vsnprintf(buffer, sizeof(buffer), fmt, args);
		va_end(args);
		g_log(buffer);
	}

	template<typename T> void SafeRelease(T*& p)
	{
		if (p != nullptr)
		{
			p->Release();
			p = nullptr;
		}
	}

	struct BackendResource
	{
		ID3D11Resource* resource;
		ID3D11ShaderResourceView* srv;
		ID3D11UnorderedAccessView* uav[kMaxUavMips];
		uint32_t uavCount;
		FfxResourceDescription description;
		bool owned;		// created by the backend (vs registered per frame by the caller)
	};

	struct BackendContext_DX11
	{
		ID3D11Device* device;

		BackendResource resources[kMaxResources];
		uint32_t nextStaticResource;
		uint32_t nextDynamicResource;

		FfxGpuJobDescription gpuJobs[kMaxGpuJobs];
		uint32_t gpuJobCount;

		ID3D11Buffer* constantBuffers[kMaxCbSlots];
		ID3D11SamplerState* samplers[2];	// s0 point clamp, s1 linear clamp (FSR2's static samplers)
	};

	BackendContext_DX11* GetBackend(FfxFsr2Interface* backendInterface)
	{
		return reinterpret_cast<BackendContext_DX11*>(backendInterface->scratchBuffer);
	}

	// ---- formats ---------------------------------------------------------------

	DXGI_FORMAT ToDxgi(FfxSurfaceFormat format)
	{
		switch (format)
		{
		case FFX_SURFACE_FORMAT_R32G32B32A32_TYPELESS:	return DXGI_FORMAT_R32G32B32A32_TYPELESS;
		case FFX_SURFACE_FORMAT_R32G32B32A32_FLOAT:		return DXGI_FORMAT_R32G32B32A32_FLOAT;
		case FFX_SURFACE_FORMAT_R16G16B16A16_FLOAT:		return DXGI_FORMAT_R16G16B16A16_FLOAT;
		case FFX_SURFACE_FORMAT_R16G16B16A16_UNORM:		return DXGI_FORMAT_R16G16B16A16_UNORM;
		case FFX_SURFACE_FORMAT_R32G32_FLOAT:			return DXGI_FORMAT_R32G32_FLOAT;
		case FFX_SURFACE_FORMAT_R32_UINT:				return DXGI_FORMAT_R32_UINT;
		case FFX_SURFACE_FORMAT_R8G8B8A8_TYPELESS:		return DXGI_FORMAT_R8G8B8A8_TYPELESS;
		case FFX_SURFACE_FORMAT_R8G8B8A8_UNORM:			return DXGI_FORMAT_R8G8B8A8_UNORM;
		case FFX_SURFACE_FORMAT_R11G11B10_FLOAT:		return DXGI_FORMAT_R11G11B10_FLOAT;
		case FFX_SURFACE_FORMAT_R16G16_FLOAT:			return DXGI_FORMAT_R16G16_FLOAT;
		case FFX_SURFACE_FORMAT_R16G16_UINT:			return DXGI_FORMAT_R16G16_UINT;
		case FFX_SURFACE_FORMAT_R16_FLOAT:				return DXGI_FORMAT_R16_FLOAT;
		case FFX_SURFACE_FORMAT_R16_UINT:				return DXGI_FORMAT_R16_UINT;
		case FFX_SURFACE_FORMAT_R16_UNORM:				return DXGI_FORMAT_R16_UNORM;
		case FFX_SURFACE_FORMAT_R16_SNORM:				return DXGI_FORMAT_R16_SNORM;
		case FFX_SURFACE_FORMAT_R8_UNORM:				return DXGI_FORMAT_R8_UNORM;
		case FFX_SURFACE_FORMAT_R8_UINT:				return DXGI_FORMAT_R8_UINT;
		case FFX_SURFACE_FORMAT_R8G8_UNORM:				return DXGI_FORMAT_R8G8_UNORM;
		case FFX_SURFACE_FORMAT_R32_FLOAT:				return DXGI_FORMAT_R32_FLOAT;
		default:										return DXGI_FORMAT_UNKNOWN;
		}
	}

	FfxSurfaceFormat FromDxgi(DXGI_FORMAT format)
	{
		switch (format)
		{
		case DXGI_FORMAT_R32G32B32A32_TYPELESS:	return FFX_SURFACE_FORMAT_R32G32B32A32_TYPELESS;
		case DXGI_FORMAT_R32G32B32A32_FLOAT:	return FFX_SURFACE_FORMAT_R32G32B32A32_FLOAT;
		case DXGI_FORMAT_R16G16B16A16_FLOAT:	return FFX_SURFACE_FORMAT_R16G16B16A16_FLOAT;
		case DXGI_FORMAT_R16G16B16A16_UNORM:	return FFX_SURFACE_FORMAT_R16G16B16A16_UNORM;
		case DXGI_FORMAT_R32G32_FLOAT:			return FFX_SURFACE_FORMAT_R32G32_FLOAT;
		case DXGI_FORMAT_R32_UINT:				return FFX_SURFACE_FORMAT_R32_UINT;
		case DXGI_FORMAT_R8G8B8A8_TYPELESS:		return FFX_SURFACE_FORMAT_R8G8B8A8_TYPELESS;
		case DXGI_FORMAT_R8G8B8A8_UNORM:		return FFX_SURFACE_FORMAT_R8G8B8A8_UNORM;
		case DXGI_FORMAT_R11G11B10_FLOAT:		return FFX_SURFACE_FORMAT_R11G11B10_FLOAT;
		case DXGI_FORMAT_R16G16_FLOAT:			return FFX_SURFACE_FORMAT_R16G16_FLOAT;
		case DXGI_FORMAT_R16G16_UINT:			return FFX_SURFACE_FORMAT_R16G16_UINT;
		case DXGI_FORMAT_R16_FLOAT:				return FFX_SURFACE_FORMAT_R16_FLOAT;
		case DXGI_FORMAT_R16_UINT:				return FFX_SURFACE_FORMAT_R16_UINT;
		case DXGI_FORMAT_R16_UNORM:				return FFX_SURFACE_FORMAT_R16_UNORM;
		case DXGI_FORMAT_R16_SNORM:				return FFX_SURFACE_FORMAT_R16_SNORM;
		case DXGI_FORMAT_R8_UNORM:				return FFX_SURFACE_FORMAT_R8_UNORM;
		case DXGI_FORMAT_R8_UINT:				return FFX_SURFACE_FORMAT_R8_UINT;
		case DXGI_FORMAT_R8G8_UNORM:			return FFX_SURFACE_FORMAT_R8G8_UNORM;
		case DXGI_FORMAT_R32_FLOAT:				return FFX_SURFACE_FORMAT_R32_FLOAT;
		case DXGI_FORMAT_R32_TYPELESS:			return FFX_SURFACE_FORMAT_R32_FLOAT;	// depth read as float
		default:								return FFX_SURFACE_FORMAT_UNKNOWN;
		}
	}

	// View format for a (possibly typeless / depth) resource format - same table as
	// the DX12 backend's convertFormat.
	DXGI_FORMAT ViewFormat(DXGI_FORMAT format)
	{
		switch (format)
		{
		case DXGI_FORMAT_R32G8X24_TYPELESS:
		case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:	return DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS;
		case DXGI_FORMAT_D32_FLOAT:				return DXGI_FORMAT_R32_FLOAT;
		case DXGI_FORMAT_R24G8_TYPELESS:
		case DXGI_FORMAT_X24_TYPELESS_G8_UINT:
		case DXGI_FORMAT_D24_UNORM_S8_UINT:		return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
		case DXGI_FORMAT_D16_UNORM:				return DXGI_FORMAT_R16_UNORM;
		case DXGI_FORMAT_R32G32B32A32_TYPELESS:	return DXGI_FORMAT_R32G32B32A32_FLOAT;
		case DXGI_FORMAT_R32G32B32_TYPELESS:	return DXGI_FORMAT_R32G32B32_FLOAT;
		case DXGI_FORMAT_R16G16B16A16_TYPELESS:	return DXGI_FORMAT_R16G16B16A16_FLOAT;
		case DXGI_FORMAT_R8G8B8A8_TYPELESS:		return DXGI_FORMAT_R8G8B8A8_UNORM;
		case DXGI_FORMAT_R32G32_TYPELESS:		return DXGI_FORMAT_R32G32_FLOAT;
		case DXGI_FORMAT_R16G16_TYPELESS:		return DXGI_FORMAT_R16G16_FLOAT;
		case DXGI_FORMAT_R10G10B10A2_TYPELESS:	return DXGI_FORMAT_R10G10B10A2_UNORM;
		case DXGI_FORMAT_B8G8R8A8_TYPELESS:		return DXGI_FORMAT_B8G8R8A8_UNORM;
		case DXGI_FORMAT_B8G8R8X8_TYPELESS:		return DXGI_FORMAT_B8G8R8X8_UNORM;
		case DXGI_FORMAT_R32_TYPELESS:			return DXGI_FORMAT_R32_FLOAT;
		case DXGI_FORMAT_R8G8_TYPELESS:			return DXGI_FORMAT_R8G8_UNORM;
		case DXGI_FORMAT_R16_TYPELESS:			return DXGI_FORMAT_R16_FLOAT;
		case DXGI_FORMAT_R8_TYPELESS:			return DXGI_FORMAT_R8_UNORM;
		default:								return format;
		}
	}

	uint32_t BytesPerPixel(DXGI_FORMAT format)
	{
		switch (format)
		{
		case DXGI_FORMAT_R32G32B32A32_TYPELESS:
		case DXGI_FORMAT_R32G32B32A32_FLOAT:	return 16;
		case DXGI_FORMAT_R16G16B16A16_FLOAT:
		case DXGI_FORMAT_R16G16B16A16_UNORM:
		case DXGI_FORMAT_R32G32_FLOAT:			return 8;
		case DXGI_FORMAT_R32_UINT:
		case DXGI_FORMAT_R32_FLOAT:
		case DXGI_FORMAT_R8G8B8A8_TYPELESS:
		case DXGI_FORMAT_R8G8B8A8_UNORM:
		case DXGI_FORMAT_R11G11B10_FLOAT:
		case DXGI_FORMAT_R16G16_FLOAT:
		case DXGI_FORMAT_R16G16_UINT:			return 4;
		case DXGI_FORMAT_R16_FLOAT:
		case DXGI_FORMAT_R16_UINT:
		case DXGI_FORMAT_R16_UNORM:
		case DXGI_FORMAT_R16_SNORM:
		case DXGI_FORMAT_R8G8_UNORM:			return 2;
		case DXGI_FORMAT_R8_UNORM:
		case DXGI_FORMAT_R8_UINT:				return 1;
		default:								return 0;
		}
	}

	// ---- views -----------------------------------------------------------------

	// Fills description + SRV (+ per-mip UAVs when the resource allows them).
	bool CreateViews(ID3D11Device* device, BackendResource& r)
	{
		D3D11_RESOURCE_DIMENSION dimension = D3D11_RESOURCE_DIMENSION_UNKNOWN;
		r.resource->GetType(&dimension);

		DXGI_FORMAT format = DXGI_FORMAT_UNKNOWN;
		UINT bindFlags = 0;
		UINT mipLevels = 1;

		if (dimension == D3D11_RESOURCE_DIMENSION_TEXTURE2D)
		{
			D3D11_TEXTURE2D_DESC desc = {};
			static_cast<ID3D11Texture2D*>(r.resource)->GetDesc(&desc);
			format = desc.Format;
			bindFlags = desc.BindFlags;
			mipLevels = desc.MipLevels;
			r.description.type = FFX_RESOURCE_TYPE_TEXTURE2D;
			r.description.width = desc.Width;
			r.description.height = desc.Height;
			r.description.depth = 1;
		}
		else if (dimension == D3D11_RESOURCE_DIMENSION_TEXTURE1D)
		{
			D3D11_TEXTURE1D_DESC desc = {};
			static_cast<ID3D11Texture1D*>(r.resource)->GetDesc(&desc);
			format = desc.Format;
			bindFlags = desc.BindFlags;
			mipLevels = desc.MipLevels;
			r.description.type = FFX_RESOURCE_TYPE_TEXTURE1D;
			r.description.width = desc.Width;
			r.description.height = 1;
			r.description.depth = 1;
		}
		else
		{
			Log("FSR2 DX11: unsupported resource dimension %d", (int)dimension);
			return false;
		}

		r.description.format = FromDxgi(format);
		r.description.mipCount = mipLevels;

		const DXGI_FORMAT viewFormat = ViewFormat(format);
		const bool is2D = dimension == D3D11_RESOURCE_DIMENSION_TEXTURE2D;

		if (bindFlags & D3D11_BIND_SHADER_RESOURCE)
		{
			D3D11_SHADER_RESOURCE_VIEW_DESC srv = {};
			srv.Format = viewFormat;
			if (is2D)
			{
				srv.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
				srv.Texture2D.MipLevels = mipLevels;
			}
			else
			{
				srv.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE1D;
				srv.Texture1D.MipLevels = mipLevels;
			}
			if (FAILED(device->CreateShaderResourceView(r.resource, &srv, &r.srv)))
			{
				Log("FSR2 DX11: SRV creation failed (format %d)", (int)viewFormat);
				return false;
			}
		}

		if (bindFlags & D3D11_BIND_UNORDERED_ACCESS)
		{
			r.uavCount = mipLevels < kMaxUavMips ? mipLevels : kMaxUavMips;
			for (uint32_t mip = 0; mip < r.uavCount; ++mip)
			{
				D3D11_UNORDERED_ACCESS_VIEW_DESC uav = {};
				uav.Format = viewFormat;
				if (is2D)
				{
					uav.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
					uav.Texture2D.MipSlice = mip;
				}
				else
				{
					uav.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE1D;
					uav.Texture1D.MipSlice = mip;
				}
				if (FAILED(device->CreateUnorderedAccessView(r.resource, &uav, &r.uav[mip])))
				{
					Log("FSR2 DX11: UAV creation failed (format %d, mip %u)", (int)viewFormat, mip);
					return false;
				}
			}
		}

		return true;
	}

	void ReleaseResource(BackendResource& r)
	{
		SafeRelease(r.srv);
		for (uint32_t mip = 0; mip < kMaxUavMips; ++mip)
			SafeRelease(r.uav[mip]);
		if (r.owned)
			SafeRelease(r.resource);
		else
			r.resource = nullptr;	// borrowed from the caller
		memset(&r, 0, sizeof(r));
	}

	// ---- shaders ---------------------------------------------------------------

	struct ShaderBlob
	{
		const BYTE* data;
		size_t size;
	};

	ShaderBlob GetPassBlob(FfxFsr2Pass pass)
	{
		switch (pass)
		{
		case FFX_FSR2_PASS_DEPTH_CLIP:					return { g_fsr2_depth_clip, sizeof(g_fsr2_depth_clip) };
		case FFX_FSR2_PASS_RECONSTRUCT_PREVIOUS_DEPTH:	return { g_fsr2_reconstruct_previous_depth, sizeof(g_fsr2_reconstruct_previous_depth) };
		case FFX_FSR2_PASS_LOCK:						return { g_fsr2_lock, sizeof(g_fsr2_lock) };
		case FFX_FSR2_PASS_ACCUMULATE:					return { g_fsr2_accumulate, sizeof(g_fsr2_accumulate) };
		case FFX_FSR2_PASS_ACCUMULATE_SHARPEN:			return { g_fsr2_accumulate_sharpen, sizeof(g_fsr2_accumulate_sharpen) };
		case FFX_FSR2_PASS_RCAS:						return { g_fsr2_rcas, sizeof(g_fsr2_rcas) };
		case FFX_FSR2_PASS_COMPUTE_LUMINANCE_PYRAMID:	return { g_fsr2_compute_luminance_pyramid, sizeof(g_fsr2_compute_luminance_pyramid) };
		case FFX_FSR2_PASS_GENERATE_REACTIVE:			return { g_fsr2_autogen_reactive, sizeof(g_fsr2_autogen_reactive) };
		case FFX_FSR2_PASS_TCR_AUTOGENERATE:			return { g_fsr2_tcr_autogen, sizeof(g_fsr2_tcr_autogen) };
		default:										return { nullptr, 0 };
		}
	}

	void CopyName(wchar_t (&dst)[64], const char* src)
	{
		size_t i = 0;
		for (; i < 63 && src[i] != 0; ++i)
			dst[i] = (wchar_t)(unsigned char)src[i];
		dst[i] = 0;
	}

	// ---- jobs ------------------------------------------------------------------

	FfxErrorCode ExecuteCompute(BackendContext_DX11* backend, ID3D11DeviceContext* context, const FfxComputeJobDescription& job)
	{
		ID3D11ShaderResourceView* srvs[kMaxSrvSlots] = {};
		ID3D11UnorderedAccessView* uavs[kMaxUavSlots] = {};
		UINT srvSlotCount = 0;
		UINT uavSlotCount = 0;

		for (uint32_t i = 0; i < job.pipeline.srvCount; ++i)
		{
			const uint32_t slot = job.pipeline.srvResourceBindings[i].slotIndex;
			if (slot >= kMaxSrvSlots)
				return FFX_ERROR_OUT_OF_RANGE;
			const BackendResource& r = backend->resources[job.srvs[i].internalIndex];
			srvs[slot] = r.srv;
			srvSlotCount = slot + 1 > srvSlotCount ? slot + 1 : srvSlotCount;
		}

		for (uint32_t i = 0; i < job.pipeline.uavCount; ++i)
		{
			const uint32_t slot = job.pipeline.uavResourceBindings[i].slotIndex;
			if (slot >= kMaxUavSlots)
				return FFX_ERROR_OUT_OF_RANGE;
			const BackendResource& r = backend->resources[job.uavs[i].internalIndex];
			const uint32_t mip = job.uavMip[i];
			uavs[slot] = mip < r.uavCount ? r.uav[mip] : nullptr;
			uavSlotCount = slot + 1 > uavSlotCount ? slot + 1 : uavSlotCount;
		}

		// Constant buffers: binding i's data goes to its register.
		ID3D11Buffer* cbs[kMaxCbSlots] = {};
		UINT cbSlotCount = 0;
		for (uint32_t i = 0; i < job.pipeline.constCount; ++i)
		{
			const uint32_t slot = job.pipeline.cbResourceBindings[i].slotIndex;
			if (slot >= kMaxCbSlots)
				return FFX_ERROR_OUT_OF_RANGE;
			ID3D11Buffer* buffer = backend->constantBuffers[slot];
			D3D11_MAPPED_SUBRESOURCE mapped = {};
			if (FAILED(context->Map(buffer, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped)))
				return FFX_ERROR_BACKEND_API_ERROR;
			const uint32_t bytes = job.cbs[i].uint32Size * sizeof(uint32_t);
			memcpy(mapped.pData, job.cbs[i].data, bytes < kCbBytes ? bytes : kCbBytes);
			context->Unmap(buffer, 0);
			cbs[slot] = buffer;
			cbSlotCount = slot + 1 > cbSlotCount ? slot + 1 : cbSlotCount;
		}

		// UAVs before SRVs: binding a UAV evicts any SRV of the same resource, and
		// this order keeps the pass's own SRVs (read-only resources) intact.
		if (uavSlotCount > 0)
			context->CSSetUnorderedAccessViews(0, uavSlotCount, uavs, nullptr);
		if (srvSlotCount > 0)
			context->CSSetShaderResources(0, srvSlotCount, srvs);
		if (cbSlotCount > 0)
			context->CSSetConstantBuffers(0, cbSlotCount, cbs);
		context->CSSetSamplers(0, 2, backend->samplers);
		context->CSSetShader(reinterpret_cast<ID3D11ComputeShader*>(job.pipeline.pipeline), nullptr, 0);

		context->Dispatch(job.dimensions[0], job.dimensions[1], job.dimensions[2]);

		// Unbind so the next pass can take these resources the other way round.
		ID3D11ShaderResourceView* nullSrvs[kMaxSrvSlots] = {};
		ID3D11UnorderedAccessView* nullUavs[kMaxUavSlots] = {};
		if (srvSlotCount > 0)
			context->CSSetShaderResources(0, srvSlotCount, nullSrvs);
		if (uavSlotCount > 0)
			context->CSSetUnorderedAccessViews(0, uavSlotCount, nullUavs, nullptr);

		return FFX_OK;
	}

	// Compute + output-merger state the jobs overwrite, restored afterwards so the
	// engine's cached device state stays truthful.
	struct SavedState
	{
		ID3D11ComputeShader* cs = nullptr;
		ID3D11ClassInstance* csInstances[256] = {};
		UINT csInstanceCount = 256;
		ID3D11ShaderResourceView* srvs[kMaxSrvSlots] = {};
		ID3D11UnorderedAccessView* uavs[kMaxUavSlots] = {};
		ID3D11Buffer* cbs[kMaxCbSlots] = {};
		ID3D11SamplerState* samplers[2] = {};
		ID3D11RenderTargetView* rtvs[D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT] = {};
		ID3D11DepthStencilView* dsv = nullptr;

		void Save(ID3D11DeviceContext* context)
		{
			context->CSGetShader(&cs, csInstances, &csInstanceCount);
			context->CSGetShaderResources(0, kMaxSrvSlots, srvs);
			context->CSGetUnorderedAccessViews(0, kMaxUavSlots, uavs);
			context->CSGetConstantBuffers(0, kMaxCbSlots, cbs);
			context->CSGetSamplers(0, 2, samplers);
			context->OMGetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs, &dsv);
		}

		void Restore(ID3D11DeviceContext* context)
		{
			context->CSSetShader(cs, csInstances, csInstanceCount);
			context->CSSetShaderResources(0, kMaxSrvSlots, srvs);
			context->CSSetUnorderedAccessViews(0, kMaxUavSlots, uavs, nullptr);
			context->CSSetConstantBuffers(0, kMaxCbSlots, cbs);
			context->CSSetSamplers(0, 2, samplers);
			context->OMSetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs, dsv);

			SafeRelease(cs);
			for (UINT i = 0; i < csInstanceCount && i < 256; ++i) SafeRelease(csInstances[i]);
			for (auto*& p : srvs) SafeRelease(p);
			for (auto*& p : uavs) SafeRelease(p);
			for (auto*& p : cbs) SafeRelease(p);
			for (auto*& p : samplers) SafeRelease(p);
			for (auto*& p : rtvs) SafeRelease(p);
			SafeRelease(dsv);
		}
	};

	// ---- FfxFsr2Interface callbacks -----------------------------------------------

	FfxErrorCode CreateBackendContextDX11(FfxFsr2Interface* backendInterface, FfxDevice device)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		memset(backend, 0, sizeof(*backend));

		ID3D11Device* d3dDevice = reinterpret_cast<ID3D11Device*>(device);
		if (d3dDevice == nullptr)
			return FFX_ERROR_NULL_DEVICE;
		d3dDevice->AddRef();
		backend->device = d3dDevice;

		// Index 0 stays empty: FFX_FSR2_RESOURCE_IDENTIFIER_NULL binds as null.
		backend->nextStaticResource = 1;
		backend->nextDynamicResource = kMaxResources - 1;

		D3D11_BUFFER_DESC cbDesc = {};
		cbDesc.ByteWidth = kCbBytes;
		cbDesc.Usage = D3D11_USAGE_DYNAMIC;
		cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
		cbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
		for (uint32_t i = 0; i < kMaxCbSlots; ++i)
		{
			if (FAILED(d3dDevice->CreateBuffer(&cbDesc, nullptr, &backend->constantBuffers[i])))
				return FFX_ERROR_BACKEND_API_ERROR;
		}

		D3D11_SAMPLER_DESC sampler = {};
		sampler.AddressU = sampler.AddressV = sampler.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
		sampler.ComparisonFunc = D3D11_COMPARISON_NEVER;
		sampler.MaxAnisotropy = 1;
		sampler.MaxLOD = D3D11_FLOAT32_MAX;
		sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_POINT;
		if (FAILED(d3dDevice->CreateSamplerState(&sampler, &backend->samplers[0])))
			return FFX_ERROR_BACKEND_API_ERROR;
		sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
		if (FAILED(d3dDevice->CreateSamplerState(&sampler, &backend->samplers[1])))
			return FFX_ERROR_BACKEND_API_ERROR;

		return FFX_OK;
	}

	FfxErrorCode GetDeviceCapabilitiesDX11(FfxFsr2Interface*, FfxDeviceCapabilities* capabilities, FfxDevice)
	{
		// Only used by backends to pick permutations; ours is fixed at build time.
		capabilities->minimumSupportedShaderModel = FFX_SHADER_MODEL_5_1;
		capabilities->waveLaneCountMin = 32;
		capabilities->waveLaneCountMax = 64;
		capabilities->fp16Supported = false;
		capabilities->raytracingSupported = false;
		return FFX_OK;
	}

	FfxErrorCode DestroyBackendContextDX11(FfxFsr2Interface* backendInterface)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		for (uint32_t i = 0; i < kMaxResources; ++i)
			ReleaseResource(backend->resources[i]);
		for (auto*& cb : backend->constantBuffers)
			SafeRelease(cb);
		for (auto*& s : backend->samplers)
			SafeRelease(s);
		SafeRelease(backend->device);
		backend->gpuJobCount = 0;
		return FFX_OK;
	}

	FfxErrorCode CreateResourceDX11(FfxFsr2Interface* backendInterface, const FfxCreateResourceDescription* desc, FfxResourceInternal* outResource)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		if (backend->nextStaticResource + 1 >= backend->nextDynamicResource)
			return FFX_ERROR_OUT_OF_MEMORY;

		const DXGI_FORMAT format = ToDxgi(desc->resourceDescription.format);
		if (format == DXGI_FORMAT_UNKNOWN || desc->resourceDescription.type != FFX_RESOURCE_TYPE_TEXTURE2D)
		{
			Log("FSR2 DX11: unsupported internal resource '%ls' (type %d, format %d)",
				desc->name ? desc->name : L"?", (int)desc->resourceDescription.type, (int)desc->resourceDescription.format);
			return FFX_ERROR_INVALID_ENUM;
		}

		D3D11_TEXTURE2D_DESC td = {};
		td.Width = desc->resourceDescription.width;
		td.Height = desc->resourceDescription.height;
		td.MipLevels = desc->resourceDescription.mipCount;	// 0 = full chain
		td.ArraySize = 1;
		td.Format = format;
		td.SampleDesc.Count = 1;
		td.Usage = D3D11_USAGE_DEFAULT;
		td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
		if (desc->usage & FFX_RESOURCE_USAGE_UAV)
			td.BindFlags |= D3D11_BIND_UNORDERED_ACCESS;
		// FFX_RESOURCE_USAGE_RENDERTARGET is a DX12 clear-path hint; every FSR2
		// clear goes through ClearUnorderedAccessViewFloat here, so it's not needed.

		// Initial data uploads directly - no separate upload resource / copy job.
		D3D11_SUBRESOURCE_DATA init = {};
		D3D11_SUBRESOURCE_DATA* initPtr = nullptr;
		if (desc->initData != nullptr && desc->initDataSize > 0)
		{
			td.MipLevels = 1;
			init.pSysMem = desc->initData;
			init.SysMemPitch = td.Width * BytesPerPixel(format);
			init.SysMemSlicePitch = init.SysMemPitch * td.Height;
			initPtr = &init;
		}

		const uint32_t index = backend->nextStaticResource++;
		BackendResource& r = backend->resources[index];
		memset(&r, 0, sizeof(r));
		r.owned = true;

		ID3D11Texture2D* texture = nullptr;
		if (FAILED(backend->device->CreateTexture2D(&td, initPtr, &texture)))
		{
			Log("FSR2 DX11: CreateTexture2D failed for '%ls' (%ux%u fmt %d)", desc->name ? desc->name : L"?", td.Width, td.Height, (int)format);
			return FFX_ERROR_BACKEND_API_ERROR;
		}
		r.resource = texture;

		if (!CreateViews(backend->device, r))
			return FFX_ERROR_BACKEND_API_ERROR;

		outResource->internalIndex = (int32_t)index;
		return FFX_OK;
	}

	FfxErrorCode RegisterResourceDX11(FfxFsr2Interface* backendInterface, const FfxResource* inResource, FfxResourceInternal* outResource)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);

		ID3D11Resource* resource = reinterpret_cast<ID3D11Resource*>(inResource->resource);
		if (resource == nullptr)
		{
			outResource->internalIndex = FFX_FSR2_RESOURCE_IDENTIFIER_NULL;
			return FFX_OK;
		}

		if (backend->nextDynamicResource <= backend->nextStaticResource)
			return FFX_ERROR_OUT_OF_MEMORY;

		const uint32_t index = backend->nextDynamicResource--;
		BackendResource& r = backend->resources[index];
		memset(&r, 0, sizeof(r));
		r.owned = false;
		r.resource = resource;

		if (!CreateViews(backend->device, r))
			return FFX_ERROR_BACKEND_API_ERROR;

		outResource->internalIndex = (int32_t)index;
		return FFX_OK;
	}

	FfxErrorCode UnregisterResourcesDX11(FfxFsr2Interface* backendInterface)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		for (uint32_t i = backend->nextDynamicResource + 1; i < kMaxResources; ++i)
			ReleaseResource(backend->resources[i]);
		backend->nextDynamicResource = kMaxResources - 1;
		return FFX_OK;
	}

	FfxResourceDescription GetResourceDescriptionDX11(FfxFsr2Interface* backendInterface, FfxResourceInternal resource)
	{
		return GetBackend(backendInterface)->resources[resource.internalIndex].description;
	}

	FfxErrorCode DestroyResourceDX11(FfxFsr2Interface* backendInterface, FfxResourceInternal resource)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		if (resource.internalIndex > 0 && (uint32_t)resource.internalIndex < kMaxResources &&
			backend->resources[resource.internalIndex].owned)
		{
			ReleaseResource(backend->resources[resource.internalIndex]);
		}
		return FFX_OK;
	}

	FfxErrorCode CreatePipelineDX11(FfxFsr2Interface* backendInterface, FfxFsr2Pass pass, const FfxPipelineDescription* desc, FfxPipelineState* outPipeline)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		memset(outPipeline, 0, sizeof(*outPipeline));

		if ((desc->contextFlags & FFX_FSR2_DX11_REQUIRED_FLAGS) != FFX_FSR2_DX11_REQUIRED_FLAGS ||
			(desc->contextFlags & FFX_FSR2_DX11_FORBIDDEN_FLAGS) != 0)
		{
			Log("FSR2 DX11: context flags 0x%x don't match the embedded shader permutation", desc->contextFlags);
			return FFX_ERROR_INVALID_ENUM;
		}

		const ShaderBlob blob = GetPassBlob(pass);
		if (blob.data == nullptr)
			return FFX_ERROR_INVALID_ENUM;

		ID3D11ComputeShader* shader = nullptr;
		if (FAILED(backend->device->CreateComputeShader(blob.data, blob.size, nullptr, &shader)))
		{
			Log("FSR2 DX11: CreateComputeShader failed for pass %d", (int)pass);
			return FFX_ERROR_BACKEND_API_ERROR;
		}

		// Recover the binding table from the bytecode - the names are what the
		// core library patches to resource identifiers.
		ID3D11ShaderReflection* reflection = nullptr;
		if (FAILED(D3DReflect(blob.data, blob.size, __uuidof(ID3D11ShaderReflection), reinterpret_cast<void**>(&reflection))))
		{
			shader->Release();
			Log("FSR2 DX11: D3DReflect failed for pass %d", (int)pass);
			return FFX_ERROR_BACKEND_API_ERROR;
		}

		D3D11_SHADER_DESC shaderDesc = {};
		reflection->GetDesc(&shaderDesc);
		for (UINT i = 0; i < shaderDesc.BoundResources; ++i)
		{
			D3D11_SHADER_INPUT_BIND_DESC bind = {};
			if (FAILED(reflection->GetResourceBindingDesc(i, &bind)))
				continue;

			switch (bind.Type)
			{
			case D3D_SIT_CBUFFER:
				if (outPipeline->constCount < FFX_MAX_NUM_CONST_BUFFERS)
				{
					FfxResourceBinding& b = outPipeline->cbResourceBindings[outPipeline->constCount++];
					b.slotIndex = bind.BindPoint;
					CopyName(b.name, bind.Name);
				}
				break;

			case D3D_SIT_TEXTURE:
			case D3D_SIT_TBUFFER:
			case D3D_SIT_STRUCTURED:
			case D3D_SIT_BYTEADDRESS:
				if (outPipeline->srvCount < FFX_MAX_NUM_SRVS)
				{
					FfxResourceBinding& b = outPipeline->srvResourceBindings[outPipeline->srvCount++];
					b.slotIndex = bind.BindPoint;
					CopyName(b.name, bind.Name);
				}
				break;

			case D3D_SIT_UAV_RWTYPED:
			case D3D_SIT_UAV_RWSTRUCTURED:
			case D3D_SIT_UAV_RWBYTEADDRESS:
			case D3D_SIT_UAV_APPEND_STRUCTURED:
			case D3D_SIT_UAV_CONSUME_STRUCTURED:
			case D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER:
				if (bind.BindPoint >= kMaxUavSlots)
				{
					Log("FSR2 DX11: pass %d binds UAV '%s' at u%u (D3D11.0 limit is %u)", (int)pass, bind.Name, bind.BindPoint, kMaxUavSlots);
					reflection->Release();
					shader->Release();
					return FFX_ERROR_OUT_OF_RANGE;
				}
				if (outPipeline->uavCount < FFX_MAX_NUM_UAVS)
				{
					FfxResourceBinding& b = outPipeline->uavResourceBindings[outPipeline->uavCount++];
					b.slotIndex = bind.BindPoint;
					CopyName(b.name, bind.Name);
				}
				break;

			default:	// samplers are fixed (s0 point, s1 linear)
				break;
			}
		}
		reflection->Release();

		outPipeline->pipeline = shader;
		outPipeline->rootSignature = nullptr;
		return FFX_OK;
	}

	FfxErrorCode DestroyPipelineDX11(FfxFsr2Interface*, FfxPipelineState* pipeline)
	{
		if (pipeline != nullptr && pipeline->pipeline != nullptr)
		{
			reinterpret_cast<ID3D11ComputeShader*>(pipeline->pipeline)->Release();
			pipeline->pipeline = nullptr;
		}
		return FFX_OK;
	}

	FfxErrorCode ScheduleGpuJobDX11(FfxFsr2Interface* backendInterface, const FfxGpuJobDescription* job)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		if (backend->gpuJobCount >= kMaxGpuJobs)
			return FFX_ERROR_OUT_OF_RANGE;
		backend->gpuJobs[backend->gpuJobCount++] = *job;
		return FFX_OK;
	}

	FfxErrorCode ExecuteGpuJobsDX11(FfxFsr2Interface* backendInterface, FfxCommandList commandList)
	{
		BackendContext_DX11* backend = GetBackend(backendInterface);
		ID3D11DeviceContext* context = reinterpret_cast<ID3D11DeviceContext*>(commandList);
		if (context == nullptr)
			return FFX_ERROR_INVALID_POINTER;

		SavedState saved;
		saved.Save(context);
		// Inputs are usually the engine's current render targets; an SRV of a
		// bound RTV/DSV would be nulled by the runtime.
		context->OMSetRenderTargets(0, nullptr, nullptr);

		FfxErrorCode result = FFX_OK;
		for (uint32_t i = 0; i < backend->gpuJobCount && result == FFX_OK; ++i)
		{
			const FfxGpuJobDescription& job = backend->gpuJobs[i];
			switch (job.jobType)
			{
			case FFX_GPU_JOB_CLEAR_FLOAT:
			{
				const BackendResource& r = backend->resources[job.clearJobDescriptor.target.internalIndex];
				if (r.uavCount > 0)
					context->ClearUnorderedAccessViewFloat(r.uav[0], job.clearJobDescriptor.color);
				break;
			}
			case FFX_GPU_JOB_COPY:
			{
				ID3D11Resource* src = backend->resources[job.copyJobDescriptor.src.internalIndex].resource;
				ID3D11Resource* dst = backend->resources[job.copyJobDescriptor.dst.internalIndex].resource;
				if (src != nullptr && dst != nullptr)
					context->CopyResource(dst, src);
				break;
			}
			case FFX_GPU_JOB_COMPUTE:
				result = ExecuteCompute(backend, context, job.computeJobDescriptor);
				break;
			default:
				break;
			}
		}

		backend->gpuJobCount = 0;
		saved.Restore(context);
		return result == FFX_OK ? FFX_OK : FFX_ERROR_BACKEND_API_ERROR;
	}
}

size_t ffxFsr2GetScratchMemorySizeDX11()
{
	return sizeof(BackendContext_DX11);
}

FfxErrorCode ffxFsr2GetInterfaceDX11(FfxFsr2Interface* outInterface, ID3D11Device* device, void* scratchBuffer, size_t scratchBufferSize)
{
	if (outInterface == nullptr || scratchBuffer == nullptr)
		return FFX_ERROR_INVALID_POINTER;
	if (scratchBufferSize < ffxFsr2GetScratchMemorySizeDX11())
		return FFX_ERROR_INSUFFICIENT_MEMORY;
	(void)device;

	outInterface->fpGetDeviceCapabilities = GetDeviceCapabilitiesDX11;
	outInterface->fpCreateBackendContext = CreateBackendContextDX11;
	outInterface->fpDestroyBackendContext = DestroyBackendContextDX11;
	outInterface->fpCreateResource = CreateResourceDX11;
	outInterface->fpRegisterResource = RegisterResourceDX11;
	outInterface->fpUnregisterResources = UnregisterResourcesDX11;
	outInterface->fpGetResourceDescription = GetResourceDescriptionDX11;
	outInterface->fpDestroyResource = DestroyResourceDX11;
	outInterface->fpCreatePipeline = CreatePipelineDX11;
	outInterface->fpDestroyPipeline = DestroyPipelineDX11;
	outInterface->fpScheduleGpuJob = ScheduleGpuJobDX11;
	outInterface->fpExecuteGpuJobs = ExecuteGpuJobsDX11;
	outInterface->scratchBuffer = scratchBuffer;
	outInterface->scratchBufferSize = scratchBufferSize;
	return FFX_OK;
}

FfxResource ffxGetResourceDX11(ID3D11Resource* resource, const wchar_t* name)
{
	FfxResource out = {};
	out.resource = resource;
	out.state = FFX_RESOURCE_STATE_COMPUTE_READ;
	if (name != nullptr)
		wcsncpy_s(out.name, name, _TRUNCATE);

	if (resource != nullptr)
	{
		D3D11_RESOURCE_DIMENSION dimension = D3D11_RESOURCE_DIMENSION_UNKNOWN;
		resource->GetType(&dimension);
		if (dimension == D3D11_RESOURCE_DIMENSION_TEXTURE2D)
		{
			D3D11_TEXTURE2D_DESC desc = {};
			static_cast<ID3D11Texture2D*>(resource)->GetDesc(&desc);
			out.description.type = FFX_RESOURCE_TYPE_TEXTURE2D;
			out.description.width = desc.Width;
			out.description.height = desc.Height;
			out.description.depth = 1;
			out.description.mipCount = desc.MipLevels;
			out.description.format = FromDxgi(desc.Format);
		}
	}
	return out;
}

void ffxFsr2SetLogCallbackDX11(FfxFsr2Dx11LogFunc callback)
{
	g_log = callback;
}
